# .github/workflows/reusable/attention.yml

name: Reusable Attention Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  attention_job:
    name: Attention Build and Test
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    env:
      CCACHE_DIR: /ws/ccache
      MAKEFLAGS: -j2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Start restoring ccache
        run: date +%d-%m-%Y > /tmp/date

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-${{ hashFiles('/tmp/date') }}
          restore-keys: |
            ccache-

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: CMake Configure
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log

      - name: Upload attention artifact
        uses: actions/upload-artifact@v4
        with:
          name: attention
          path: /ws/attention

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache
