# .github/workflows/package.yml

name: Package Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package-and-deploy:
    name: Package and Deploy
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ccache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-package-${{ runner.os }}-${{ hashFiles('**/*.cpp', '**/*.h') }}
          restore-keys: |
            ccache-package-${{ runner.os }}-
            ccache-package-

      - name: Build and Package
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          # Add packaging commands here
          # e.g., make package

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: build/

      - name: Deploy Package
        if: github.ref == 'refs/heads/main'
        run: |
          # Add deployment commands here
          # e.g., upload to a server or repository
          echo "Deploying package..."
