rotate_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rotate_joint
    joint_speed: 0.8
    motor:
        id: 0
        init: 2290
        min: 1240
        max: 3340
        acceleration: 10
pitch1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pitch1_joint
    joint_speed: 0.2
    motor:
        id: 1
        init: 2089
        min: 1850
        max: 2180
roll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: roll_joint
    joint_speed: 0.3
    motor:
        id: 2
        init: 1512
        min: 1330
        max: 1645
pitch2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pitch2_joint
    joint_speed: 0.2
    motor:
        id: 3
        init: 2015
        min: 1800
        max: 2240
jaw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: jaw_joint
    joint_speed: 1
    motor:
        id: 4
        init: 550
        min: 425
        max: 715

#Pau2Motors config
pau2motors:
    topics:
        cmd_neck_pau: neck_pitch_top;neck_pitch_bottom;neck_roll;neck_base
        cmd_eyes_pau: Eyes_Pitch;Eye_L;Eye_R
        cmd_face_pau: Cheek-Squint_L;Cheek-Squint_R;Eyelid-Lower_R;Eyelid-Lower_L;Eyelid-Upper_R;Eyelid-Upper_L;Frown_R;Brow-Outer_L;Smile_R;Smile_L;Lip-Lower_L;Lip_Upper_C;Sneer_R;Lip-Upper_L;Lip-Lower_R;Lip-Lower_C;Brow-Inner_L;Frown_L;Lip-Upper_R;Sneer_L;Brow_Outer_R;Brow-Inner_R;Jaw
        faceshift_track: Eyelid-Lower_R;Eyelid-Lower_L;Eyelid-Upper_R;Eyelid-Upper_L;Brow-Outer_L;Smile_R;Smile_L;Brow-Inner_L;Brow_Outer_R;Brow-Inner_R;Jaw;eyes_pitch;leye_yaw;reye_yaw;neck_pitch_top;neck_pitch_bottom;neck_roll;neck_base
        #faceshift_track: Eyelid-Lower_R;Eyelid-Lower_L;Eyelid-Upper_R;Eyelid-Upper_L

    motors:

    # Eyes
      Eyes_Pitch:
        binding:
          parser:
            name: getproperty
            property: m_eyeGazeLeftPitch
          function:
            - name: linear
              min: 0.4
              max: -0.4
          hardware:
            name: pololu
            topic: arthur_eyes/cmd_pololu
            joint_name: Eyes_Pitch
            speed: 200
            acceleration: 100
        min: -0.58
        max: 1.117

      Eye_L:
        binding:
          parser:
            name: getproperty
            property: m_eyeGazeLeftYaw
          function:
            - name: linear
              min: 0.8
              max: -0.75
          hardware:
            name: pololu
            topic: arthur_eyes/cmd_pololu
            joint_name: Eye_L
            speed: 200
            acceleration: 100
        min: -0.58
        max: 0.55

      Eye_R:
        binding:
          parser:
            name: getproperty
            property: m_eyeGazeRightYaw
          function:
            - name: linear
              min: 0.8
              max: -0.8
          hardware:
            name: pololu
            topic: arthur_eyes/cmd_pololu
            joint_name: Eye_R
            speed: 200
            acceleration: 100
        min: -0.68
        max: 0.45


    # ---Neck---

      neck_pitch_bottom:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              scale: -0.5
              translate: 0
          hardware:
            name: dynamixel
            topic: pitch1_controller/command
        min: -1.57
        max: 1.57

      neck_pitch_top:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              scale: 0.5
              translate: 0
          hardware:
            name: dynamixel
            topic: pitch2_controller/command
        min: -1.57
        max: 1.57

      neck_roll:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: x
            - name: linear
              scale: 1.0
              translate: 0
          hardware:
            name: dynamixel
            topic: roll_controller/command
        min: -1.57
        max: 1.57

      neck_base:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: y
            - name: linear
              scale: 1
              translate: 0
          hardware:
            name: dynamixel
            topic: rotate_controller/command
        min: -1.7
        max: 1.7

# -----------------------------Face--------------------------------
      Cheek-Squint_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: 46_CheekSquint_L
          function:
            - name: linear
              min: 0
              max: 0.4
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Cheek-Squint_L
            speed: 200
            acceleration: 100
        min: -1.547
        max: -0.249


      Cheek-Squint_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: 47_CheekSquint_R
          function:
            - name: linear
              min: 0
              max: 0.4
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Cheek-Squint_R
            speed: 200
            acceleration: 100
        min: -0.457
        max: 1.422


      Eyelid-Lower_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: 01_EyeBlink_R;03_EyeSquint_R;09_EyeOpen_R
          function:
            - name: weightedsum
              imin: 0.4
              terms:
              - {min: 0, max: 0.8, imax: 1}
              - {min: 0, max: 1, imax: 0.7}
              - {min: 0, max: 1, imax: 0.0}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Eyelid-Lower_R
            speed: 400
            acceleration: 400
        min: -0.813
        max: 0.084


      Eyelid-Lower_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: 00_EyeBlink_L;02_EyeSquint_L;08_EyeOpen_L
          function:
            - name: weightedsum
              imin: 0.59
              terms:
              - {min: 0, max: 0.8, imax: 0.0}
              - {min: 0, max: 0.1, imax: 0.3}
              - {min: 0, max: 1, imax: 1}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Eyelid-Lower_L
            speed: 400
            acceleration: 400
        min: 0.052
        max: 0.826


      Eyelid-Upper_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: 01_EyeBlink_R;09_EyeOpen_R
          function:
            - name: weightedsum
              imin: 0.673
              terms:
              - {min: 0, max: 0.8, imax: 0.0}
              - {min: 0, max: 0.8, imax: 1}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Eyelid-Upper_R
            speed: 400
            acceleration: 400
        min: -0.551
        max: 0.877


      Eyelid-Upper_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: 00_EyeBlink_L;08_EyeOpen_L
          function:
            - name: weightedsum
              imin: 0.288
              terms:
              - {min: 0, max: 0.8, imax: 1.0}
              - {min: 0, max: 1, imax: 0.0}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Eyelid-Upper_L
            speed: 400
            acceleration: 400
        min: -0.199
        max: 1.229



      Frown_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: 27_MouthFrown_R
          function:
            - name: linear
              min: 0.8
              max: 0
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Frown_R
            speed: 200
            acceleration: 100
        min: -1.57
        max: -0.341


      Brow-Outer_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: 17_BrowsU_O_L;14_BrowsD_O_L
          function:
            - name: weightedsum
              imin: 0.308
              terms:
              - {min: 0, max: 0.7, imax: 0.8}
              - {min: 0, max: 0.5, imax: 0.0}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Brow-Outer_L
            speed: 200
            acceleration: 100
        min: -0.27
        max: 1.165


      Smile_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: 29_MouthSmile_R
          function:
            - name: linear
              min: 0
              max: 1
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Smile_R
            speed: 200
            acceleration: 100
        min: -1.246
        max: -0.09


      Smile_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: 28_MouthSmile_L
          function:
            - name: linear
              min: 1
              max: 0
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Smile_L
            speed: 200
            acceleration: 100
        min: -1.547
        max: 0.005


      Lip-Lower_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: 37_LipsLowerDown_L;42_ChinLowerRaise
          function:
            - name: weightedsum
              imin: 0.216
              terms:
              - {min: 0, max: 0.6, imax: 1.0}
              - {min: 0, max: 0.8, imax: 0}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Lip-Lower_L
            speed: 200
            acceleration: 100
        min: -0.805
        max: 0.703


      Lip_Upper_C:
        binding:
          parser:
            name: fsshapekey
            shapekey: 38_LipsUpperOpen;43_ChinUpperRaise;36_LipsUpperUp_R;36_LipsUpperUp_L
          function:
            - name: weightedsum
              imin: 0.373
              terms:
              - {min: 0, max: 1, imax: 1.0}
              - {min: 0, max: 1, imax: 1}
              - {min: 0, max: 0.8, imax: 0.6}
              - {min: 0, max: 0.8, imax: 0.6}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Lip_Upper_C
            speed: 200
            acceleration: 100
        min: -1.095
        max: 0.284


      Sneer_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: 44_Sneer_R
          function:
            - name: linear
              min: 0
              max: 1
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Sneer_R
            speed: 200
            acceleration: 100
        min: -1.57
        max: 0.005


      Lip-Upper_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: 36_LipsUpperUp_L
          function:
            - name: linear
              min: 0.8
              max: 0
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Lip-Upper_L
            speed: 200
            acceleration: 100
        min: -0.784
        max: 0.251


      Lip-Lower_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: 37_LipsLowerDown_R;42_ChinLowerRaise
          function:
            - name: weightedsum
              imin: 0.675
              terms:
              - {min: 0, max: 0.6, imax: 0}
              - {min: 0, max: 0.8, imax: 1}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Lip-Lower_R
            speed: 200
            acceleration: 100
        min: -0.613
        max: 1.396


      Lip-Lower_C:
        binding:
          parser:
            name: fsshapekey
            shapekey: 42_ChinLowerRaise;39_LipsLowerOpen
          function:
            - name: weightedsum
              imin: 0.7
              terms:
              - {min: 0, max: 0.8, imax: 0}
              - {min: 0, max: 0.5, imax: 1}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Lip-Lower_C
            speed: 200
            acceleration: 100
        min: -0.457
        max: 1.396


      Brow-Inner_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: 17_BrowsU_I_L;14_BrowsD_I_L
          function:
            - name: weightedsum
              imin: 0.515
              terms:
              - {min: 0, max: 1, imax: 1}
              - {min: 0, max: 0.3, imax: 0}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Brow-Inner_L
            speed: 200
            acceleration: 100
        min: -1.57
        max: 1.512


      Frown_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: 26_MouthFrown_L
          function:
            - name: linear
              min: 0
              max: 0.8
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Frown_L
            speed: 200
            acceleration: 100
        min: -0.11
        max: 1.165



      Lip-Upper_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: 36_LipsUpperUp_R
          function:
            - name: linear
              min: 0
              max: 1
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Lip-Upper_R
            speed: 200
            acceleration: 100
        min: 0.355
        max: 1.512


      Sneer_L:
        binding:
          parser:
            name: fsshapekey
            shapekey: 44_Sneer_L
          function:
            - name: linear
              min: 1
              max: 0
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Sneer_L
            speed: 200
            acceleration: 100
        min: -0.457
        max: 1.165


      Brow_Outer_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: 15_BrowsD_O_R;18_BrowsU_O_R
          function:
            - name: weightedsum
              imin: 0.6
              terms:
              - {min: 0, max: 0.7, imax: 1}
              - {min: 0, max: 0.5, imax: 0}
          hardware:
            name: pololu
            topic: arthur_face/cmd_pololu
            joint_name: Brow_Outer_R
            speed: 200
            acceleration: 100
        min: -0.668
        max: 1.165




      Brow-Inner_R:
        binding:
          parser:
            name: fsshapekey
            shapekey: 18_BrowsU_I_R
          function:
            - name: linear
              min: 0.3
              max: 0
          hardware:
            name: pololu
            topic: arthur_eyes/cmd_pololu
            joint_name: Brow-Inner_R
            speed: 200
            acceleration: 100
        min: -1.57
        max: -0.457

      Jaw:
        binding:
          parser:
            name: fsshapekey
            shapekey: 21_JawOpen
          function:
            - name: linear
              min: 0
              max: 0.4
          hardware:
            name: dynamixel
            topic: jaw_controller/command
        min: -0.2
        max: 0.65


