# .github/workflows/cogutil.yml

name: CogUtil Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test CogUtil
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    env:
      CCACHE_DIR: /ws/ccache
      MAKEFLAGS: -j2
    steps:
      - name: Checkout CogUtil Repository
        uses: actions/checkout@v4

      - name: Set up Ccache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-cogutil-${{ runner.os }}-${{ hashFiles('**/*.cpp', '**/*.h') }}
          restore-keys: |
            ccache-cogutil-${{ runner.os }}-
            ccache-cogutil-

      - name: Configure Build
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build Tests
        run: |
          cd build
          make tests

      - name: Run Tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Upload CogUtil Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cogutil
          path: build/
