version: 2.1

jobs:
  # Job for CogUtil
  cogutil:
    docker:
      - image: opencog/opencog-deps
        user: root
        environment:
          CCACHE_DIR: /ws/ccache
    working_directory: /ws/cogutil
    steps:
      - checkout
      - run:
          name: Start restoring ccache
          command: date +%d-%m-%Y > /tmp/date
      - restore_cache:
          keys:
            - ccache-{{ checksum "/tmp/date" }}
            - ccache-
      - run:
          name: CMake Configure
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cd build && make -j2
      - run:
          name: Build tests
          command: cd build && make -j2 tests
      - run:
          name: Run tests
          command: cd build && make -j2 check ARGS=-j2
      - run:
          name: Print test log
          command: cat build/tests/Testing/Temporary/LastTest.log
          when: always
      - persist_to_workspace:
          root: /ws/
          paths:
            - cogutil
            - ccache

  # Job for AtomSpace
  atomspace:
    docker:
      - image: opencog/opencog-deps
        user: root
        environment:
          CCACHE_DIR: /ws/ccache
    working_directory: /ws/atomspace
    steps:
      - attach_workspace:
          at: /ws
      - run:
          name: Install CogUtil
          command: cd /ws/cogutil/build && make install && ldconfig
      - run:
          name: Checkout AtomSpace
          command: git clone --depth 1 https://github.com/$CIRCLE_PROJECT_USERNAME/atomspace .
      - run:
          name: CMake Configure
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cd build && make -j2
      - run:
          name: Build tests
          command: cd build && make -j2 tests
      - run:
          name: Run tests
          command: cd build && make -j2 check ARGS=-j2
      - run:
          name: Install AtomSpace
          command: cd build && make install && ldconfig
      - persist_to_workspace:
          root: /ws/
          paths:
            - atomspace
            - ccache

  # Job for PLN
  pln:
    docker:
      - image: opencog/opencog-deps
        user: root
        environment:
          CCACHE_DIR: /ws/ccache
    working_directory: /ws/pln
    steps:
      - attach_workspace:
          at: /ws
      - run:
          name: Install AtomSpace
          command: cd /ws/atomspace/build && make install && ldconfig
      - run:
          name: Install CogUtil
          command: cd /ws/cogutil/build && make install && ldconfig
      - run:
          name: Checkout PLN
          command: git clone --depth 1 https://github.com/$CIRCLE_PROJECT_USERNAME/pln .
      - run:
          name: CMake Configure
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cd build && make -j2
      - run:
          name: Build tests
          command: cd build && make -j2 tests
      - run:
          name: Install PLN
          command: cd build && make -j2 install && ldconfig
      - run:
          name: Run tests
          command: cd build && make -j2 check ARGS=-j2
      - persist_to_workspace:
          root: /ws/
          paths:
            - pln
            - ccache

  # Job for URE
  ure:
    docker:
      - image: opencog/opencog-deps
        user: root
        environment:
          CCACHE_DIR: /ws/ccache
    working_directory: /ws/ure
    steps:
      - attach_workspace:
          at: /ws
      - run:
          name: Install CogUtil
          command: cd /ws/cogutil/build && make install && ldconfig
      - run:
          name: Install AtomSpace
          command: cd /ws/atomspace/build && make install && ldconfig
      - run:
          name: Checkout URE
          command: git clone --depth 1 https://github.com/$CIRCLE_PROJECT_USERNAME/ure .
      - run:
          name: CMake Configure
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cd build && make -j2
      - run:
          name: Build tests
          command: cd build && make -j2 tests
      - run:
          name: Install URE
          command: cd build && make install && ldconfig
      - persist_to_workspace:
          root: /ws/
          paths:
            - ure
            - ccache

  # Job for Miner
  miner:
    docker:
      - image: opencog/opencog-deps
        user: root
        environment:
          CCACHE_DIR: /ws/ccache
    working_directory: /ws/miner
    steps:
      - attach_workspace:
          at: /ws
      - run:
          name: Install CogUtil
          command: cd /ws/cogutil/build && make install && ldconfig
      - run:
          name: Install AtomSpace
          command: cd /ws/atomspace/build && make install && ldconfig
      - run:
          name: Install URE
          command: cd /ws/ure/build && make install && ldconfig
      - run:
          name: Checkout Miner
          command: git clone --depth 1 https://github.com/$CIRCLE_PROJECT_USERNAME/miner .
      - run:
          name: CMake Configure
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cd build && make -j2
      - run:
          name: Build tests
          command: cd build && make -j2 tests
      - run:
          name: Install Miner
          command: cd build && make install && ldconfig
      - persist_to_workspace:
          root: /ws/
          paths:
            - miner
            - ccache

workflows:
  version: 2
  build-test-package:
    jobs:
      - cogutil
      - atomspace:
          requires:
            - cogutil
      - pln:
          requires:
            - atomspace
            - cogutil
      - ure:
          requires:
            - atomspace
            - cogutil
      - miner:
          requires:
            - ure
            - cogutil
            - atomspace
