# .github/workflows/reusable/ure.yml

name: Reusable URE Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  ure_job:
    name: URE Build and Test
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    env:
      CCACHE_DIR: /ws/ccache
      MAKEFLAGS: -j2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Start restoring ccache
        run: date +%d-%m-%Y > /tmp/date

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-${{ hashFiles('/tmp/date') }}
          restore-keys: |
            ccache-

      - name: Set number of make jobs
        run: echo "MAKEFLAGS=-j2" >> $GITHUB_ENV

      - name: Install CogUtil
        run: |
          git clone --depth 1 https://github.com/opencog/cogutil /ws/cogutil
          mkdir -p /ws/cogutil/build
          cd /ws/cogutil/build && cmake .. && make -j2 && make -j2 install
          ldconfig

      - name: Install AtomSpace
        run: |
          git clone --depth 1 https://github.com/opencog/atomspace /ws/atomspace
          mkdir -p /ws/atomspace/build
          cd /ws/atomspace/build && cmake .. && make -j2 && make -j2 install
          ldconfig

      - name: Install Unify (URE dependency)
        run: |
          git clone --depth 1 https://github.com/opencog/unify /ws/unify
          mkdir -p /ws/unify/build
          cd /ws/unify/build && cmake .. && make -j2 && make -j2 install
          ldconfig

      - name: CMake Configure
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build tests
        run: |
          cd build
          make tests

      - name: Run tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Print test log
        if: always()
        run: |
          cat build/tests/Testing/Temporary/LastTest.log

      - name: Upload ure artifact
        uses: actions/upload-artifact@v4
        with:
          name: ure
          path: build/

      - name: Install URE
        run: |
          cd build && make -j2 install && ldconfig

      - name: Upload ccache artifact
        uses: actions/upload-artifact@v4
        with:
          name: ccache
          path: /ws/ccache
