# .github/workflows/ci.yml

name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cogutil:
    name: Build and Test CogUtil
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    steps:
      - name: Checkout CogUtil Repository
        uses: actions/checkout@v4
        with:
          repository: your-org/cogutil
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add build and test steps for CogUtil here

  atomspace:
    name: Build and Test AtomSpace
    needs: cogutil
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    steps:
      - name: Checkout AtomSpace Repository
        uses: actions/checkout@v4
        with:
          repository: your-org/atomspace
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add build and test steps for AtomSpace here

  asmoses:
    name: Build and Test AsmoSES
    needs: atomspace
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    steps:
      - name: Checkout AsmoSES Repository
        uses: actions/checkout@v4
        with:
          repository: your-org/asmoses
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add build and test steps for AsmoSES here

  ure:
    name: Build and Test URE
    needs: asmoses
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    steps:
      - name: Checkout URE Repository
        uses: actions/checkout@v4
        with:
          repository: your-org/ure
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add build and test steps for URE here

  unify:
    name: Build and Test Unify
    needs: ure
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    steps:
      - name: Checkout Unify Repository
        uses: actions/checkout@v4
        with:
          repository: your-org/unify
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add build and test steps for Unify here

  package:
    name: Package and Deploy
    needs: unify
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Package
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          # Add packaging commands here
          # e.g., make package

      - name: Deploy Package
        run: |
          # Add deployment commands here
          # e.g., upload to a server or repository
          echo "Deploying package..."
