name: Clean Up

on:
  workflow_call:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Clean up
      run: |
        rm -rf *.git
        rm -rf repo_list.txt
        echo "Temporary files cleaned up"
