# .github/workflows/miner.yml

name: Miner Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Miner
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    env:
      CCACHE_DIR: /ws/ccache
      MAKEFLAGS: -j2
    steps:
      - name: Checkout Miner Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Install CogUtil
          git clone https://github.com/your-org/cogutil.git /tmp/cogutil
          cd /tmp/cogutil
          mkdir build && cd build
          cmake ..
          make && make install
          # Install AtomSpace
          git clone https://github.com/your-org/atomspace.git /tmp/atomspace
          cd /tmp/atomspace
          mkdir build && cd build
          cmake ..
          make && make install
          # Install CogServer
          git clone https://github.com/your-org/cogserver.git /tmp/cogserver
          cd /tmp/cogserver
          mkdir build && cd build
          cmake ..
          make && make install
          # Install URE
          git clone https://github.com/your-org/ure.git /tmp/ure
          cd /tmp/ure
          mkdir build && cd build
          cmake ..
          make && make install

      - name: Set up Ccache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-miner-${{ runner.os }}-${{ hashFiles('**/*.cpp', '**/*.h') }}
          restore-keys: |
            ccache-miner-${{ runner.os }}-
            ccache-miner-

      - name: Configure Build
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build Tests
        run: |
          cd build
          make tests

      - name: Run Tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Upload Miner Artifact
        uses: actions/upload-artifact@v4
        with:
          name: miner
          path: build/
