# .github/workflows/ure.yml

name: URE Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test URE
    runs-on: ubuntu-latest
    container:
      image: opencog/opencog-deps
      options: --user root
    env:
      CCACHE_DIR: /ws/ccache
      MAKEFLAGS: -j2
    steps:
      - name: Checkout URE Repository
        uses: actions/checkout@v4

      - name: Set up Ccache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-ure-${{ runner.os }}-${{ hashFiles('**/*.cpp', '**/*.h') }}
          restore-keys: |
            ccache-ure-${{ runner.os }}-
            ccache-ure-

      - name: Install CogUtil
        run: |
          git clone --depth 1 https://github.com/opencog/cogutil /ws/cogutil
          mkdir -p /ws/cogutil/build
          cd /ws/cogutil/build && cmake .. && make -j2 && make -j2 install
          ldconfig

      - name: Install AtomSpace
        run: |
          git clone --depth 1 https://github.com/opencog/atomspace /ws/atomspace
          mkdir -p /ws/atomspace/build
          cd /ws/atomspace/build && cmake .. && make -j2 && make -j2 install
          ldconfig

      - name: Install Unify (URE dependency)
        run: |
          git clone --depth 1 https://github.com/opencog/unify /ws/unify
          mkdir -p /ws/unify/build
          cd /ws/unify/build && cmake .. && make -j2 && make -j2 install
          ldconfig

      - name: Configure Build
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build Tests
        run: |
          cd build
          make tests

      - name: Run Tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Upload URE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ure
          path: build/
