name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install Doxygen
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz

      # Step 3: Generate Doxygen documentation
      - name: Generate Doxygen Documentation
        run: |
          doxygen Doxyfile

      # Step 4: Upload documentation as an artifact
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: docs/  # Replace with the actual path to the generated documentation

  deploy-docs:
    needs: generate-docs
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/  # Replace with the actual path to the generated documentation
