[package]
name = "logic-query"
version = "0.1.0"
edition = "2021"

[build]
rustflags = "-C opt-level=3 -C target-cpu=native"

[dependencies]
pathmap = { workspace=true }
mork-frontend = { workspace=true }
mork-bytestring = { workspace=true }
