safe:
    Frown_R_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: Frown-R_joint
        joint_speed: 1.1
        motor:
            id: 6
            init: 2048
            min: 1600
            max: 2650
            acceleration: 20

    Smile_R_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: Smile-R_joint
        joint_speed: 1.1
        motor:
            id: 9
            init: 2048
            min: 1450
            max: 2600
            acceleration: 20

    Smile_L_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: Smile-L_joint
        joint_speed: 1.1
        motor:
            id: 8
            init: 2048
            min: 1600
            max: 2600
            acceleration: 20

    Frown_L_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: Frown-L_joint
        joint_speed: 1.1
        motor:
            id: 7
            init: 2048
            min: 1600
            max: 2700
            acceleration: 20

    Jaw_Up_Down_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: Jaw-Up-Down_joint
        joint_speed: 5
        motor:
            id: 5
            init: 1970
            min: 1970
            max: 3000
            acceleration: 50

    Upper_Gimbal_L_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: Upper-Gimbal-L_joint
        joint_speed: 0.4
        motor:
            id: 4
            init: 2080
            min: 1200
            max: 2970
            acceleration: 20

    Upper_Gimbal_R_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: Upper-Gimbal-R_joint
        joint_speed: 0.4
        motor:
            id: 3
            init: 2240
            min: 1200
            max: 3090
            acceleration: 10

    Lower_Gimbal_L_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: Lower-Gimbal-L_joint
        joint_speed: 0.35
        motor:
            id: 2
            init: 2228
            min: 1700
            max: 2672
            acceleration: 10

    Lower_Gimbal_R_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: Lower-Gimbal-R_joint
        joint_speed: 0.35
        motor:
            id: 1
            init: 1868
            min: 1180
            max: 2250
            acceleration: 10

    Neck_Rotation_controller:
        controller:
            package: dynamixel_controllers
            module: joint_position_controller
            type: JointPositionController
        joint_name: Neck-Rotation_joint
        joint_speed: 0.8
        motor:
            id: 0
            init: 1994
            min: 1130
            max: 2830
            acceleration: 1


pau2motors:
    topics:
        neck_pau: Upper-Gimbal-L;Upper-Gimbal-R;Lower-Gimbal-L;Lower-Gimbal-R;Neck-Rotation
        head_pau: EyeTurn-R;EyeTurn-L;Lower-Lid-L;LowerLid-R;Upper-Lid-R;Upper-Lid-L;Brow-Outer-L;Brow-Outer-R;Brow-Inner-L;Brow-Inner-R;Cheek-Squint;Eyes-Up-Down;Brow-Center;oo-Drawstring-Upper-R;oo-Drawstring-Lower-R
        no_pau: Frown-R;Frown-L;Smile-R;Smile-L;Jaw-Up-Down;EyeTurn-R;EyeTurn-L;LowerLid-R;Lower-Lid-L;Upper-Lid-R;Upper-Lid-L;Eyes-Up-Down
        lips_pau: Jaw-Up-Down;Lower-Lip-L;Lower-Lip-R;Lower-Lip-Center;Upper-Lip-L;Upper-Lip-R;Upper-Lip-Center;EE-L;EE-R;Frown-R;Frown-L;Smile-R;Smile-L

# Robot voice
voice: katherine 
lipsync: True
#safety_rules:
#    Smile-L:
#        - type: timing
#          direction: min
#          extreme: 0.35
#          t1: 1
#          t2: 1
#          t3: 5
#          t4: 1
#    Smile-R:
#        - type: timing
#          direction: min
#          extreme: 0.5
#          t1: 1
#          t2: 1
#          t3: 5
#          t4: 1
#    Frown-L:
#        - type: timing
#          direction: max
#          extreme: 0.6
#          t1: 1
#          t2: 1
#          t3: 5
#          t4: 1
#    Frown-R:
#        - type: timing
#          direction: max
#          extreme: 0.6
#          t1: 1
#          t2: 1
#          t3: 5
#          t4: 1
#    Jaw-Up-Down:
#        - type: timing
#          direction: max
#          extreme: 0.6
#          t1: 1
#          t2: 1
#          t3: 5
#          t4: 1
