name: Copy and Commit Yaml files

on:
  workflow_dispatch:
  push:
    branches:
      - main  # adjust if your main branch has a different name

jobs:
  copy-commit-scm:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Allow pushing commits back

      - name: Copy .yml files preserving directory structure
        run: |
          mkdir -p copied-yml
          find . -name '*.yml' -print0 | cpio -pdmv0 copied-yml

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add copied-yml/
          git commit -m "Automated: Copy YML files preserving directory structure" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
